version: '3.8'
services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats_user
      POSTGRES_PASSWORD: stats_password
    ports:
      - "5433:5432"
    volumes:
      - stats_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats_user -d stats"]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-server:
    build:
      context: ./stats-service/stats-server
      dockerfile: Dockerfile
    container_name: stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats_user
      SPRING_DATASOURCE_PASSWORD: stats_password
      SERVER_PORT: 9090
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ewm-db:
     image: postgres:16.1
     container_name: ewm-db
     environment:
       POSTGRES_DB: ewm
       POSTGRES_USER: ewm_user
       POSTGRES_PASSWORD: ewm_password
     ports:
       - "5434:5432"
     volumes:
       - ewm_db_data:/var/lib/postgresql/data
     healthcheck:
       test: ["CMD-SHELL", "pg_isready -U ewm_user -d ewm"]
       interval: 10s
       timeout: 5s
       retries: 5

  ewm-service:
     build:
       context: ./main-service
       dockerfile: Dockerfile
     container_name: ewm-service
     environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
       SPRING_DATASOURCE_USERNAME: ewm_user
       SPRING_DATASOURCE_PASSWORD: ewm_password
       STATS_SERVER_URL: http://stats-server:9090
       SERVER_PORT: 8080
     ports:
       - "8080:8080"
     depends_on:
       ewm-db:
         condition: service_healthy
       stats-server:
         condition: service_healthy

volumes:
  stats_db_data:
  ewm_db_data: